---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openshift
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: odc
  annotations:
    jira/project-key: ODC
    #jira/component: <example-component> # optional, you might skip this value to fetch data for all components
spec:
  type: service
  lifecycle: production
  owner: guests
  system: openshift
