# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugins
  annotations:
    backstage.io/source-location: url:https://github.com/janus-idp/backstage-plugins
    sonarqube.org/project-key: janus-idp_backstage-plugins
spec:
  type: service
  lifecycle: production
  owner: guests
  system: rhdh-system
