# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jira-example
  annotations:
    # roadie jira plugin
    jira/project-key: ODC
    #jira/component: <example-component> # optional, you might skip this value to fetch data for all components

    # AxisCommunications jira-dashboard
    jira.com/project-key: ODC
    #jira.com/components: component,component,component # Jira component name separated with a comma. The Roadie Backstage Jira Plugin Jira annotation `/component` is also supported here by default
    #jira.com/filter-ids: 12345,67890 # Jira filter id separated with a comma
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
