apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adr-example
  annotations:
    backstage.io/adr-location: https://github.com/christoph-jerolimov/backstage-experiments/tree/main/adr/adrs
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: no-adr-example
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
