---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugins
  annotations:
    sonarqube.org/project-key: janus-idp_backstage-plugins
spec:
  type: plugins
  lifecycle: production
  owner: guests
  system: backstage
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-showcase
  annotations:
    sonarqube.org/project-key: janus-idp_backstage-showcase
spec:
  type: app
  lifecycle: production
  owner: guests
  system: backstage
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: operator
  annotations:
    sonarqube.org/project-key: janus-idp_operator
spec:
  type: operator
  lifecycle: production
  owner: guests
  system: backstage
