site_name: long-nav

plugins:
  - techdocs-core

nav:
  - Index: index.md
  - '1': index.md
  - '1.1': index.md
  - '1.2': index.md
  - '1.3': index.md
  - '1.4': index.md
  - '1.5': index.md
  - '1.6': index.md
  - '1.7': index.md
  - '1.8': index.md
  - '1.9': index.md
  - '1.10': index.md
  - '2': index.md
  - '2.1': index.md
  - '2.2': index.md
  - '2.3': index.md
  - '2.4': index.md
  - '2.5': index.md
  - '2.6': index.md
  - '2.7': index.md
  - '2.8': index.md
  - '2.9': index.md
  - '2.10': index.md
  - '3': index.md
  - '3.1': index.md
  - '3.2': index.md
  - '3.3': index.md
  - '3.4': index.md
  - '3.5': index.md
  - '3.6': index.md
  - '3.7': index.md
  - '3.8': index.md
  - '3.9': index.md
  - '3.10': index.md
  - '4': index.md
  - '4.1': index.md
  - '4.2': index.md
  - '4.3': index.md
  - '4.4': index.md
  - '4.5': index.md
  - '4.6': index.md
  - '4.7': index.md
  - '4.8': index.md
  - '4.9': index.md
  - '4.10': index.md
  - '5': index.md
  - '5.1': index.md
  - '5.2': index.md
  - '5.3': index.md
  - '5.4': index.md
  - '5.5': index.md
  - '5.6': index.md
  - '5.7': index.md
  - '5.8': index.md
  - '5.9': index.md
  - '5.10': index.md
  - '6': index.md
  - '6.1': index.md
  - '6.2': index.md
  - '6.3': index.md
  - '6.4': index.md
  - '6.5': index.md
  - '6.6': index.md
  - '6.7': index.md
  - '6.8': index.md
  - '6.9': index.md
  - '6.10': index.md
  - '7': index.md
  - '7.1': index.md
  - '7.2': index.md
  - '7.3': index.md
  - '7.4': index.md
  - '7.5': index.md
  - '7.6': index.md
  - '7.7': index.md
  - '7.8': index.md
  - '7.9': index.md
  - '7.10': index.md
  - '8': index.md
  - '8.1': index.md
  - '8.2': index.md
  - '8.3': index.md
  - '8.4': index.md
  - '8.5': index.md
  - '8.6': index.md
  - '8.7': index.md
  - '8.8': index.md
  - '8.9': index.md
  - '8.10': index.md
  - '9': index.md
  - '9.1': index.md
  - '9.2': index.md
  - '9.3': index.md
  - '9.4': index.md
  - '9.5': index.md
  - '9.6': index.md
  - '9.7': index.md
  - '9.8': index.md
  - '9.9': index.md
  - '9.10': index.md
  - '10': index.md
  - '10.1': index.md
  - '10.2': index.md
  - '10.3': index.md
  - '10.4': index.md
  - '10.5': index.md
  - '10.6': index.md
  - '10.7': index.md
  - '10.8': index.md
  - '10.9': index.md
  - '10.10': index.md
  - END: index.md
